services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: {{MYSQL_USER}}
      SPRING_DATASOURCE_PASSWORD: {{MYSQL_PASSWORD}}
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: {{MYSQL_DATABASE}}
      MYSQL_ROOT_PASSWORD: {{MYSQL_ROOT_PASSWORD}}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
