services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zawmyothantsin
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: zawmyothantsin
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
